'From Cuis 6.0 [latest update: #6053] on 24 October 2023 at 3:25:40 pm'!
'Description '!
!provides: 'CuisApp' 1 2!
!requires: 'UI-Components' nil nil nil!
!requires: 'Gettext' nil nil nil!
!requires: 'SVG' nil nil nil!
SystemOrganization addCategory: #CuisApp!


!classDefinition: #CuisApp category: #CuisApp!
Object subclass: #CuisApp
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'CuisApp'!
!classDefinition: 'CuisApp class' category: #CuisApp!
CuisApp class
	instanceVariableNames: ''!

